narration_segment_task:
  description: >
    - Given the long temple description text in the provided data: {text}, split the text into smaller chunks, each containing fewer than 5000 characters.
    - Leverage your understanding to identify natural breakpoints, to ensure that the logical flow is maintained.
    - Ensure that no sentence or key idea is arbitrarily split, so that when the chunks are later combined, the narrative remains smooth and engaging.
    
    Important Notes:
      - Donot use your knowledge while performing this task, always rely on the input.
      - The segmentation should prioritize readability and continuity for TTS output.
      - Ensure that each segment is coherent and the overall narrative remains intact when stitched together.
      - Ensure that no information is lost.

      
  expected_output: >
    - A structured list of text chunks, each less than 5000 characters, that together form a seamless and engaging narrative about the temple.
    - The text should be formatted as natural speech, removing unnecessary special characters, headings, and symbols that might affect pronunciation.
    - The output should be formatted as numbered paragraphs, where each paragraph begins with a number followed by a period and space (e.g., "1. ...", "2. ...").
  agent: narration_segment_agent
