temple_tour_guide_task:
  description: >
    - Utilize the information related to each temple present in the `data` :{data}, to generate a structured summary. 
    Important Notes:  
      - You should use only the provided data and must not use your knowledge.
      - Ensure historical and cultural accuracy, maintaining respect for traditions.  
      
  expected_output: >
    For each temple, categorize the content into relevant sections such as:
      - Religious Significance : Extracted detail from retrieved chunk
      - History & Architecture : Extracted detail from retrieved chunk
      - Legends : Extracted detail from retrieved chunk
      - Interesting Facts : Extracted detail from retrieved chunk
      - Festivals & Rituals (if mentioned) : Extracted detail from retrieved chunk
      - Any Other Important Information : Extracted detail from retrieved chunk
      Ensure each section contains relevant details extracted from the chunks.
  
  agent: temple_tour_guide_agent
