narrative_analyzer_task:
  description: >
    - Analyze the full temple description passage provided in `data` :{data}, and break it down into visually distinct scenes suitable for image generation.
    Important Notes:
      - Work only with the provided passage without adding external knowledge.
      - Identify key visual moments such as major architectural features, rituals, deity depictions, festivals, processions, or environmental settings.
      - Ensure logical segmentation that follows the natural storytelling and narrative flow of the passage.

  expected_output: >
    A structured list where each item represents a meaningful visual scene, with a brief explanation of what the scene depicts.
    Example:
      - Scene 1: Grand entrance of the temple showcasing intricate carvings.
      - Scene 2: Temple sanctum with the presiding deity adorned with jewels.
      - Scene 3: Temple courtyard bustling during a festival celebration.

  agent: narrative_analyzer_agent

image_count_estimator_task:
  description: >
    - Based on the `scenes` output from the `narrative_analyzer_agent`, estimate the optimal number of images needed to visualize the description effectively, considering voiceover pacing and visual coherence.
    Important Notes:
      - If scenes are too minor or visually similar, merge them smartly.
      - Maintain smooth storytelling without unnecessary scene fragmentation.
      - Voiceover narration speed: 120–150 words per minute.

  expected_output: >
    A finalized scene list for image generation, specifying:
      - Final Scene Number
      - Brief Scene Description
    Example:
      - Scene 1: Entrance and bustling courtyard combined.
      - Scene 2: Sanctum with glowing deity.

  agent: image_count_estimator_agent

  context: [narrative_analyzer_task]

prompt_writer_task:
  description: >
    - For each final scene decided by the `image_count_estimator_agent`, craft a vivid, detailed, and imaginative prompt optimized for generating Studio Ghibli-style art using DALL-E.
    Important Notes:
      - Focus on evoking a painterly, whimsical, soft, and magical atmosphere.
      - Always clearly anchor the scene in Hinduism and Indian culture: use terms like "Hindu temple," "Vedic rituals," "Sanskrit scriptures," "South Indian priest,"Sri Chakra","India."
      - Include key visual elements: temple architecture (Dravidian, Nagara, Vesara), deity depictions, rituals, environment settings (time of day, weather, season), traditional attire (dhoti, angavastram, saree), festival scenes, and natural surroundings.
      - Explicitly avoid any references to Buddhism, Chinese, Zen, or Japanese temples or monks.
      - Use adjectives like "dreamy," "ethereal," "vibrant," "whimsical," "magical light," "lush environment."
      - Mention "Ghibli-style," "painterly," or "hand-drawn anime style" explicitly in the prompt to guide DALL-E.
      - Avoid hyperrealism terms like "8k," "ultra realistic," or technical photography terms.

  expected_output: >
    Generate only the prompts, each clearly numbered. Do not include any titles, scene names, descriptions, or headings. The output should strictly follow this format:

    1. <prompt 1>
    2. <prompt 2>
    3. <prompt 3>
    ...

    Example:
    1. A dreamy South Indian temple entrance (Gopuram) surrounded by lush greenery, intricate colorful Hindu carvings glowing under the soft morning sun, sacred Sanskrit inscriptions, whimsical atmosphere, painterly Ghibli-style art, vibrant colors, magical feeling.
    2. Inside a serene ancient Kanchipuram temple sanctum, golden oil lamps cast a warm magical glow on a beautifully adorned Hindu deity, delicate floral garlands, misty sacred aura, hand-drawn anime style, ethereal South Indian ambiance.

  agent: prompt_writer_agent

  context: [image_count_estimator_task]
